//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditRuleClassification
    {
        public int AuditRuleClassification1 { get; set; }
        public Nullable<int> AuditQuestionId { get; set; }
        public Nullable<int> DynamicControlId { get; set; }
        public string RuleExpression { get; set; }
        public string RuleType { get; set; }
        public string DynamicControlLabel { get; set; }
        public string Reject_Remarks { get; set; }
    }
}
