//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditQuestion
    {
        public int AuditQuestionsID { get; set; }
        public string AuditQuestion1 { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Order_no { get; set; }
    }
}
