//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarchartData
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public int todaycount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
