//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEDPreviousEmployerDetail
    {
        public int PreviousEmployerDetailId { get; set; }
        public string PreviousEmployerName { get; set; }
        public string PreviousEmployerStreetAddress { get; set; }
        public string PreviousEmployerCity { get; set; }
        public string PreviousEmployerState { get; set; }
        public string PreviousEmployerZipcode { get; set; }
        public string PreviousEmploymentStartDate { get; set; }
        public string PreviousEmploymentEndDate { get; set; }
        public string ReasonForLeavingPreviousEmployments { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> TempCPScreenDataID { get; set; }
        public Nullable<int> CountForFaxId { get; set; }
        public string EmploymentGapFrom { get; set; }
        public string EmploymentGapTo { get; set; }
        public string ReasonForEmploymentGap { get; set; }
    }
}
