//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentEmployerDetail
    {
        public int CurrentEmployerDetailID { get; set; }
        public string CurrentEmployerName { get; set; }
        public string CurrentEmploymentStartDate { get; set; }
        public string CurrentEmployerStreetAddress { get; set; }
        public string CurrentEmployerCity { get; set; }
        public string CurrentEmployerState { get; set; }
        public string CurrentEmployerZipcode { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> TempCPScreenDataID { get; set; }
        public Nullable<int> CountForFaxId { get; set; }
    }
}
