//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_stat_table
    {
        public System.DateTime Date { get; set; }
        public int AgentId { get; set; }
        public int ClientId { get; set; }
        public int DocumentTypeId { get; set; }
        public int FaxId { get; set; }
        public int DocumentId { get; set; }
        public int Mismatch_data_Entry_Count { get; set; }
        public int Field_Entered_Count { get; set; }
        public int Document_Data_Entry_Time { get; set; }
    }
}
