//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverFilesValue
    {
        public int id { get; set; }
        public Nullable<int> CPScreenDataId { get; set; }
        public Nullable<int> Faxid { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> CountForFaxID { get; set; }
        public Nullable<int> DynamicControlID { get; set; }
        public string DynamicControl { get; set; }
        public string DynamicControlValue { get; set; }
        public Nullable<int> Processed { get; set; }
    }
}
