//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicControlValue
    {
        public int DyanamicControlValueID { get; set; }
        public int TempCPScreenDataID { get; set; }
        public int DynamicControlID { get; set; }
        public string DynamicControlValueText { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoboActivitiesID { get; set; }
        public Nullable<int> CountForFaxId { get; set; }
    
        public virtual CMS_CPScreenData_Temp CMS_CPScreenData_Temp { get; set; }
        public virtual DynamicControl DynamicControl { get; set; }
    }
}
