//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelErrorLog
    {
        public int ExcelErrorLogId { get; set; }
        public string DocumentName { get; set; }
        public string Error { get; set; }
        public string OtherReason { get; set; }
        public string DateProcessed { get; set; }
        public string DateFound { get; set; }
        public string DriverId { get; set; }
        public string ClientAccount { get; set; }
        public string ProcessorWhoMadeError { get; set; }
        public string ProcessorWhoCaughtError { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OutCome { get; set; }
        public string ItemType { get; set; }
        public string Path { get; set; }
    }
}
