//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaxidProcessingSummry
    {
        public int Faxid { get; set; }
        public System.DateTime TimeReceived { get; set; }
        public Nullable<System.DateTime> EntryProcessingQueue { get; set; }
        public int NoofPages { get; set; }
        public Nullable<int> NoofDocs { get; set; }
        public Nullable<System.DateTime> DataEntryStart { get; set; }
        public Nullable<System.DateTime> DataEntryFinished { get; set; }
        public Nullable<System.DateTime> RobotProcessingStart { get; set; }
        public Nullable<System.DateTime> RobotProcessingFinished { get; set; }
        public Nullable<int> TotalDataEntryTime { get; set; }
        public Nullable<int> TotalRobotProcessTime { get; set; }
        public Nullable<System.DateTime> LastDocComplete { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
