//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LebellingLog
    {
        public int LabellingID { get; set; }
        public Nullable<int> FaxID { get; set; }
        public Nullable<System.DateTime> LabellingStartTime { get; set; }
        public Nullable<System.DateTime> LabellingEndTime { get; set; }
        public string LabellingText { get; set; }
    }
}
