//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        public int LoginDetailsId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateOfLogin { get; set; }
        public Nullable<System.DateTime> DateOfLogOut { get; set; }
        public string IPAddress { get; set; }
        public string Event { get; set; }
        public Nullable<int> Attempts { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
