//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousResidenceDetail
    {
        public int PreviousResidenceDetailID { get; set; }
        public string PreviousResidenceStreetAddress { get; set; }
        public string PreviousResidenceCity { get; set; }
        public string PreviousResidenceState { get; set; }
        public string PreviousResidenceZipcode { get; set; }
        public string PreviousResidenceDuration { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> TempCPScreenDataID { get; set; }
        public Nullable<int> CountForFaxId { get; set; }
    }
}
