//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTaskMatchDetail
    {
        public int TempTaskMatchDetailsId { get; set; }
        public Nullable<int> TempCPScreenDataID { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<bool> IsMatched { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
    }
}
