//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTaskAssignment
    {
        public int TempTaskAssignmentID { get; set; }
        public int FaxID { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfModification { get; set; }
        public int TempCPScreenDataID { get; set; }
        public int ProcessStatus { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<int> NoOfPagesCompleted { get; set; }
    
        public virtual CMS_CPScreenData_Temp CMS_CPScreenData_Temp { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
