//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.DocumentTypes = new HashSet<DocumentType>();
            this.LoginDetails = new HashSet<LoginDetail>();
            this.TempTaskAssignments = new HashSet<TempTaskAssignment>();
        }
    
        public int UserDetailsID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public int FADVUserID { get; set; }
        public int RoleId { get; set; }
        public string Password { get; set; }
        public int LoginAttempt { get; set; }
        public Nullable<bool> LocktheAccount { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfModification { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentType> DocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginDetail> LoginDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempTaskAssignment> TempTaskAssignments { get; set; }
    }
}
